/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign Case */
        patch: operations["assign_case_cases__case_id__assignment_patch"];
        trace?: never;
    };
    "/cases/{case_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Audit */
        get: operations["get_case_audit_cases__case_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Decide Category
         * @description Accept the suggested category (send the same value) or override it (send another).
         */
        put: operations["decide_category_cases__case_id__category_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Decide Priority
         * @description Accept the suggested priority (send the same value) or override it (send another).
         */
        put: operations["decide_priority_cases__case_id__priority_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/vulnerability-indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Indicator
         * @description Add an indicator the AI missed, with a quote from the complaint as evidence (US-3.5).
         */
        post: operations["add_indicator_cases__case_id__vulnerability_indicators_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/vulnerability-indicators/{indicator_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Decide Indicator
         * @description Confirm or reject an indicator. A rejected one stays visible as rejected (US-3.4).
         */
        put: operations["decide_indicator_cases__case_id__vulnerability_indicators__indicator_id__decision_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description The process is up. Used by Docker / Azure Container Apps liveness probes.
         */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description The process can reach the database.
         */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventRead */
        AuditEventRead: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Correlation Id */
            correlation_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Field */
            field: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** New Value */
            new_value: unknown | null;
            /** Old Value */
            old_value: unknown | null;
            source: components["schemas"]["AuditSource"];
        };
        /**
         * AuditSource
         * @enum {string}
         */
        AuditSource: "system" | "accepted_suggestion" | "override" | "handler";
        /** CaseAssign */
        CaseAssign: {
            /** Assigned To User Id */
            assigned_to_user_id: string | null;
        };
        /** CaseCreate */
        CaseCreate: {
            /** Body */
            body: string;
            /**
             * External Message Id
             * @description Email Message-ID. Submitting the same id twice returns the existing case.
             */
            external_message_id?: string | null;
            /**
             * Received At
             * @description When the complaint was received. Defaults to now.
             */
            received_at?: string | null;
            /**
             * Sender Email
             * Format: email
             */
            sender_email: string;
            /** Sender Name */
            sender_name?: string | null;
            /** Subject */
            subject: string;
        };
        /** CaseList */
        CaseList: {
            /** Items */
            items: components["schemas"]["CaseSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** CaseRead */
        CaseRead: {
            /** Assigned To User Id */
            assigned_to_user_id: string | null;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            deadline_tracking?: components["schemas"]["DeadlineTrackingRead"] | null;
            /** External Message Id */
            external_message_id: string | null;
            final_category: components["schemas"]["Category"] | null;
            final_priority: components["schemas"]["Priority"] | null;
            /** Final Response Deadline At */
            final_response_deadline_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Reference */
            reference: string;
            resolution_type: components["schemas"]["ResolutionType"] | null;
            /** Resolved At */
            resolved_at: string | null;
            /**
             * Review Reason
             * @description Why the case needs a person, when its status says so
             */
            review_reason?: string | null;
            /** Sender Email */
            sender_email: string;
            /** Sender Name */
            sender_name: string | null;
            /** Src Deadline At */
            src_deadline_at: string | null;
            status: components["schemas"]["CaseStatus"];
            /** Subject */
            subject: string;
            /** @description Null until the analysis completes (US-2.4) */
            suggestion?: components["schemas"]["SuggestionRead"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vulnerability Indicators */
            vulnerability_indicators?: components["schemas"]["IndicatorRead"][];
        };
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "new" | "analysing" | "awaiting_review" | "needs_human_review" | "in_progress" | "resolved";
        /**
         * CaseSummary
         * @description Lighter shape for lists: no body.
         */
        CaseSummary: {
            /** Assigned To User Id */
            assigned_to_user_id: string | null;
            deadline_tracking?: components["schemas"]["DeadlineTrackingRead"] | null;
            /** Final Response Deadline At */
            final_response_deadline_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Open Vulnerability Flags
             * @description Indicators not rejected: pending or confirmed
             * @default 0
             */
            open_vulnerability_flags: number;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Reference */
            reference: string;
            /** Sender Email */
            sender_email: string;
            /** Src Deadline At */
            src_deadline_at: string | null;
            status: components["schemas"]["CaseStatus"];
            /** Subject */
            subject: string;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "fees_and_charges" | "service_quality" | "account_administration" | "payments_and_transfers" | "lending_and_affordability" | "fraud_and_scams" | "advice_and_mis_selling" | "collections_and_arrears" | "other";
        /** CategoryDecision */
        CategoryDecision: {
            category: components["schemas"]["Category"];
        };
        /** DeadlineProgressRead */
        DeadlineProgressRead: {
            /**
             * Business Days Remaining
             * @description 0 = due today; negative = days overdue
             */
            business_days_remaining: number;
            /**
             * Deadline At
             * Format: date-time
             */
            deadline_at: string;
            /** Is Overdue */
            is_overdue: boolean;
        };
        /**
         * DeadlineTrackingRead
         * @description Calculated on every read, because it depends on today's date (US-4.6, US-4.7).
         */
        DeadlineTrackingRead: {
            /** @description Null once the case is resolved */
            final_response: components["schemas"]["DeadlineProgressRead"] | null;
            /**
             * Resolved In Time
             * @description Null while the case is open
             */
            resolved_in_time: boolean | null;
            /** @description Null once the case is resolved */
            src: components["schemas"]["DeadlineProgressRead"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndicatorCreate
         * @description A vulnerability indicator the AI missed. The quote must be in the complaint.
         */
        IndicatorCreate: {
            /** Evidence Quote */
            evidence_quote: string;
            indicator_type: components["schemas"]["IndicatorType"];
        };
        /**
         * IndicatorDecision
         * @enum {string}
         */
        IndicatorDecision: "pending" | "confirmed" | "rejected";
        /** IndicatorDecisionRequest */
        IndicatorDecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirmed" | "rejected";
        };
        /** IndicatorRead */
        IndicatorRead: {
            /** Decided At */
            decided_at: string | null;
            /** Decided By User Id */
            decided_by_user_id: string | null;
            decision: components["schemas"]["IndicatorDecision"];
            driver: components["schemas"]["VulnerabilityDriver"];
            /** Evidence Quote */
            evidence_quote: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            indicator_type: components["schemas"]["IndicatorType"];
            source: components["schemas"]["IndicatorSource"];
        };
        /**
         * IndicatorSource
         * @enum {string}
         */
        IndicatorSource: "ai" | "handler";
        /**
         * IndicatorType
         * @enum {string}
         */
        IndicatorType: "physical_illness" | "mental_health" | "disability" | "bereavement" | "relationship_breakdown" | "job_loss" | "financial_hardship" | "low_capability";
        /**
         * Priority
         * @enum {string}
         */
        Priority: "low" | "medium" | "high" | "urgent";
        /** PriorityDecision */
        PriorityDecision: {
            priority: components["schemas"]["Priority"];
        };
        /**
         * ResolutionType
         * @enum {string}
         */
        ResolutionType: "src" | "final_response";
        /**
         * SuggestionRead
         * @description What the AI suggested. The case's final_* fields hold what a person decided.
         */
        SuggestionRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            suggested_category: components["schemas"]["Category"] | null;
            suggested_priority: components["schemas"]["Priority"] | null;
            /** Summary */
            summary: string | null;
        };
        /** UserRead */
        UserRead: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["UserRole"];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "handler" | "team_lead";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VulnerabilityDriver
         * @description The four drivers of vulnerability in FCA FG21/1.
         * @enum {string}
         */
        VulnerabilityDriver: "health" | "life_events" | "resilience" | "capability";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cases_cases_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CaseStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Duplicate: existing case returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_case_cases__case_id__assignment_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseAssign"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_audit_cases__case_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_category_cases__case_id__category_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_priority_cases__case_id__priority_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriorityDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_indicator_cases__case_id__vulnerability_indicators_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndicatorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_indicator_cases__case_id__vulnerability_indicators__indicator_id__decision_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                indicator_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndicatorDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
}
